version: '3.7'
services:
    aplicacion:
        build:
            context: ./aplicacion
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - mysql

    mysql:
        restart: always
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: tienda
            DB_USERNAME: root
            DB_PASSWORD:

networks:
    app:
        driver: bridge
